# Generated by Django 5.2.8 on 2025-11-18 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_medicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('horario_inicial', models.TimeField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.medicacao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.paciente')),
            ],
        ),
    ]
