# Generated by Django 5.2.8 on 2025-11-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_prescricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_real', models.DateTimeField()),
                ('comentario', models.TextField(blank=True)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.prescricao')),
            ],
        ),
    ]
