# Generated by Django 5.2.8 on 2025-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0006_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
