# Generated by Django 5.2.8 on 2025-11-24 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0007_questioncategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionarios.paciente'),
            preserve_default=False,
        ),
    ]
