# Generated by Django 5.2.8 on 2025-11-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0009_questionarioresposta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionarioResposta',
        ),
    ]
