# Generated by Django 5.2.8 on 2025-11-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0011_acompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
