# Generated by Django 5.2.8 on 2025-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lembrete",
            name="destinatario",
            field=models.CharField(
                choices=[("joao", "João (Pai)"), ("maria", "Maria (Mãe)")],
                default="joao",
                max_length=20,
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="registroadministracao",
            name="status",
            field=models.CharField(
                choices=[
                    ("TOMEI", "Tomei/Dei a medicação"),
                    ("ESQUECI", "Esqueci"),
                    ("RECUSEI", "Bebê recusou"),
                    ("VOMITOU", "Vomitou após tomar"),
                    ("SISTEMA_ADD", "✨ Cadastro Novo"),
                    ("SISTEMA_EDIT", "✏️ Edição de Dados"),
                    ("ESTOQUE_UP", "📦 Atualização de Estoque"),
                ],
                max_length=20,
            ),
        ),
    ]
