# Generated by Django 5.2.6 on 2025-11-18 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dosagem', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('via', models.CharField(choices=[('ORAL', 'Oral'), ('IM', 'Intramuscular')], max_length=10)),
                ('duracao_dias', models.IntegerField()),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('cuidados_especiais', models.TextField(blank=True)),
                ('bebe_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('canal_preferido', models.CharField(default='APP', max_length=20)),
                ('tolerancia_minutos', models.IntegerField(default=30)),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='medicacoes.medicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_total_ml', models.FloatField()),
                ('consumo_diario_estimado_ml', models.FloatField()),
                ('alerta_baixo_estoque', models.BooleanField(default=False)),
                ('medicacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='medicacoes.medicacao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('TOMEI', 'Tomei/Dei a medicação'), ('ESQUECI', 'Esqueci'), ('RECUSEI', 'Bebê recusou'), ('VOMITOU', 'Vomitou após tomar')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='medicacoes.medicacao')),
            ],
        ),
    ]
